project:
  type: book
  output-dir: _book
  
book:
  title: "R Reference"
  author: "JJB"
  description: | 
    TBA
  #cover-image: images/cover.png
  site-url: https://textbooks.thecoatlessprofessor.com/r-reference
  repo-url: https://github.com/coatless-textbooks/r-reference
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: "Graphics"
      chapters: 
        - base-r-graphics.qmd
    - part: "Configuration"
      chapters: 
        - r-environment-variables.qmd
    - part: "Parallelization"
    - part: "Compiled Code"
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true

# Register Adsense plugin to appear on all pages
adsense:
  publisher-id: ca-pub-4979996562647159

filters:
- adsense